/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCauHinhQuyTrinh: typeof import('./components/QuyTrinh/AddCauHinhQuyTrinh.vue')['default']
    AddNode: typeof import('./components/QuyTrinh/AddNode.vue')['default']
    Alert: typeof import('./components/Alert/Alert.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BtnDiaLogYesNo: typeof import('./components/Common/BtnDiaLogYesNo.vue')['default']
    CBCheckDanhSachNode: typeof import('./components/QuyTrinh/CBCheckDanhSachNode.vue')['default']
    CBCheckNhanSu: typeof import('./components/Common/CBCheckNhanSu.vue')['default']
    CBCheckNhanSuNode: typeof import('./components/QuyTrinh/CBCheckNhanSuNode.vue')['default']
    CBCheckPhongBan: typeof import('./components/Common/CBCheckPhongBan.vue')['default']
    CBCheckPhongBanNode: typeof import('./components/QuyTrinh/CBCheckPhongBanNode.vue')['default']
    CbPhanQuyen: typeof import('./components/Common/CbPhanQuyen.vue')['default']
    CBPhongBan: typeof import('./components/Common/CBPhongBan.vue')['default']
    DanhSachUser: typeof import('./components/UserAcount/DanhSachUser.vue')['default']
    Datetimepicker: typeof import('./components/Common/datetimepicker.vue')['default']
    MainHome: typeof import('./components/Main/MainHome.vue')['default']
    Navigation: typeof import('./components/Main/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimePicker: typeof import('./components/Common/TimePicker.vue')['default']
  }
}
