/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert/Alert.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    MainHome: typeof import('./components/Main/MainHome.vue')['default']
    MainPage: typeof import('./components/Main/MainPage.vue')['default']
    Navigation: typeof import('./components/Main/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
